### ISSUE TITLE
SIARD2 export module, MS SQL server: Error while exporting trigger

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#228] opened 2016-07-14 08:25 UTC
This is a pilot blocker.
For a database on MS SQL server I tried to export to SIARD2 with the beta5.jar.

I got the following error:

Fatal error while converting the database (Error while exporting trigger: trigger triggeredAction cannot be black) com.databasepreservation.model.exception.ModuleException: Error while exporting trigger: trigger triggeredAction cannot be black

[stud.txt](https://github.com/keeps/db-preservation-toolkit/files/363263/stud.txt)

----------
**Tasklist (added by @chalkos)**
- [x] fix typo (black -> blank)
- [ ] identify the problem
- [ ] fix the problem

**Comment by chalkos** [comment] 2016-07-14 09:51
black? what a typo, I need to change that to "blank" :sweat_smile:

Are you able to identify the problematic trigger? It seems like MS SQL import module is not being able to identify some information about the trigger.

I would like you to do one or both of these things:

1) Could you look for any "handled SQLException" somewhere in the log file? It should be a "DEBUG" message and may provide some more information about the error. It should also have a [stack trace](http://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors) accompanying that message, I also need that part.
(however there may not be any of those messages at all)

2) The module uses a query similar to this one to get the trigger information:

```
SELECT
  o.name AS TRIGGER_NAME,
  CAST(OBJECTPROPERTY(id, 'ExecIsAfterTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsInsteadOfTrigger') AS char(1)) AS ACTION_TIME,
  CAST(OBJECTPROPERTY(id, 'ExecIsInsertTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsUpdateTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsDeleteTrigger') AS char(1)) AS TRIGGER_EVENT,
  OBJECT_DEFINITION(o.id) AS TRIGGERED_ACTION,
  tab.name AS TABLE_NAME,
  s.name AS SCHEMA_NAME
FROM sysobjects o
  INNER JOIN sys.tables tab ON o.parent_obj = tab.object_id
  INNER JOIN sys.schemas s ON tab.schema_id = s.schema_id
WHERE
  o.type = 'TR'
;
```

Could you try running it yourself on your MS SQL Server? The problematic column is `TRIGGERED_ACTION` which should have a value but it does not (maybe it's NULL?). Try to find the triggers that do not have a value for `TRIGGERED_ACTION` and give me some information on those, because those are the problematic ones.

**Comment by PhillipTommerholt** [comment] 2016-07-14 11:30
1) There are no messages of that sort
2) I will try to do that, but first:

I have found a problem in the table where DBPTK crashes. There are no triggers in the table, but an user ("public") has been granted permission to the table (delete, insert, select, update). However, there are no effective permissions since the user does not exist in the database. (Error: Cannot execute as the database principal because the principal "public" does not exist, this type of principal cannot be impersonated, or you do not have permission.)

A quick google search suggests this might be a problem due to the fact that I am working on a restored backup.

Can this be related to the DBPTK error?

**Comment by chalkos** [comment] 2016-07-14 13:04
Maybe. But if there are no triggers in that table that seems unlikely. Unless the permissions corruption that seems to be happening is hiding an existing trigger for that table...

The execution of the query in my previous comment should provide us some more details.

**Comment by PhillipTommerholt** [comment] 2016-07-15 07:02
There is only one trigger.
The `TRIGGERED_ACTION` goes like this:

```
CREATE TRIGGER [triggername] ON dbo.tablename1
FOR INSERT, UPDATE
AS
  insert 
  into tablename2
  select columnname1,columnname2 = convert(int,substring(columnname3,9,6))
  from tablename1
  where columnname4 = '38' and not exists 
    (select columnname3 from tablename2 where tablename1.columname1 = tablename2.columnname1)
```

**Comment by chalkos** [comment] 2016-07-15 08:48
Could you check in the log (or report file) if this table is one of the tables that DBPTK is trying to export to SIARD?

**Comment by PhillipTommerholt** [comment] 2016-07-15 08:50
DBPTK is trying to export this table, yes.

**Comment by chalkos** [comment] 2016-07-15 08:52
The SCHEMA_NAME and TABLE_NAME in the query results correspond to `dbo` and `tablename1` that you referenced above?

**Comment by PhillipTommerholt** [comment] 2016-07-15 08:58
Yes.

**Comment by PhillipTommerholt** [comment] 2016-07-15 09:19
Oh sorry, I think I misunderstood your question.
No, it has nothing to do with the table with granted permissions.

**Comment by chalkos** [comment] 2016-07-15 09:43
In fact, DBPTK uses this query:

```
SELECT
  o.name AS TRIGGER_NAME,
  CAST(OBJECTPROPERTY(id, 'ExecIsAfterTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsInsteadOfTrigger') AS char(1)) AS ACTION_TIME,
  CAST(OBJECTPROPERTY(id, 'ExecIsInsertTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsUpdateTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsDeleteTrigger') AS char(1)) AS TRIGGER_EVENT,
  OBJECT_DEFINITION(o.id) AS TRIGGERED_ACTION,
  tab.name AS TABLE_NAME,
  s.name AS SCHEMA_NAME
FROM sysobjects o
  INNER JOIN sys.tables tab ON o.parent_obj = tab.object_id
  INNER JOIN sys.schemas s ON tab.schema_id = s.schema_id
WHERE
  o.type = 'TR' AND
  s.name = 'xxxxxxxx' AND tab.name = 'yyyyyyy'
;
```

And I thought I could provide you a shortcut by listing all the trigger info to find the problematic one, but it doesn't seem to be working... :/


*So here comes the non-shortcut way:*

I would like you to run DBPTK, but instead of creating a SIARD, use the list-tables export module to list all the tables that would be exported to SIARD.

Then, for each table, run the query above, replacing `xxxxxxxx` with the schema name and `yyyyyyy` with the table name.

You should note down the tables which return one or more triggers through this query.

For those, check if any of them have a NULL in the TRIGGERED_ACTION, and if they do, do the other fields have good values? or are also null?

**Comment by PhillipTommerholt** [comment] 2016-07-15 11:26
The database has 288 tables...

I have isolated the table which had the trigger: 

```
CREATE TRIGGER [triggername] ON dbo.tablename1
FOR INSERT, UPDATE
AS
  insert 
  into tablename2
  select columnname1,columnname2 = convert(int,substring(columnname3,9,6))
  from tablename1
  where columnname4 = '38' and not exists 
    (select columnname3 from tablename2 where tablename1.columname1 = tablename2.columnname1)
```

And it is indeed this table(/trigger) that cannot be exported. I am getting the exact same error when I try to export this table only.

**Comment by chalkos** [comment] 2016-07-15 11:38
I didn't realise that there were that many, sorry :sweat_smile:

This is strange. I'm going to need some more info. Since I can't have the database (and a minimal example might be hard to produce), I will be creating a special DBPTK version that logs more info about the triggers, to try to find the source for this problem. I'm just finishing up on another task and then I'll create this version.

**Comment by chalkos** [comment] 2016-07-15 11:39
Could you also try running the query (the last one I gave you) but only for the problematic table (and respective schema)?

**Comment by PhillipTommerholt** [comment] 2016-07-15 11:43
Yes, I already did. Both queries give the same result. 

Btw, this databasehas one schema only.

**Comment by chalkos** [comment] 2016-07-15 13:09
I'll create the special version then.

**Comment by chalkos** [comment] 2016-07-18 09:46
Try the conversion with this version: 
[dbptk-app-2.0.0-beta5-228-1.zip](https://github.com/keeps/db-preservation-toolkit/files/368681/dbptk-app-2.0.0-beta5-228-1.zip)

Look for the new debug information in the log file, they all start with `issue228: ` to be easier to find.
This should tell us which triggers are being exported and the information they contain.

I don't know if you noticed, but DBPTK creates multiple log files (it creates a new one when the file gets too big). Have this in mind when looking for the debug messages. The files are named
* dbptk-app.log.txt
* dbptk-app-*date*.*number*.log.txt
It should be ok to delete (or move the logs somewhere else) and then start DBPTK.

PS: also look for the `handled SQLException` error message in the log file(s)

**Comment by PhillipTommerholt** [comment] 2016-07-18 11:00
Thx Bruno.

I only exported the problematic table with the trigger, and here you have the edited log:
[triggerlog.txt](https://github.com/keeps/db-preservation-toolkit/files/368835/triggerlog.txt)

In the log you can first find a `handled SQLException` looking for remarks (on the trigger?) and a more comprehensive error `issue228`.

**Comment by PhillipTommerholt** [comment] 2016-07-18 11:06
I guess the problem is that DBPTK is looking for a comment on a trigger, which it can't find since triggers can't have comments. Great detective fix, Bruno :+1:

**Comment by PhillipTommerholt** [comment] 2016-07-18 11:51
I am looking into documentation of triggers. 
At a first glance it looks like that the SQL:standard includes documentation, but I haven't found any of the big vendors that have actually implemented it.

**Comment by chalkos** [comment] 2016-07-18 14:23
The problem is not the comment/remark, because it is optional in SIARD and so it not being there is not an error.

The problem is in
```
Trigger{
  actionTime='AFTER',
  name='xxxxxxxx',
  triggerEvent='UPDATE',
  aliasList='null',
  triggeredAction='null',
  description='null'
}
```

The `triggeredAction` should contain the query you obtained above (here: https://github.com/keeps/db-preservation-toolkit/issues/228#issuecomment-232927977), but instead it is NULL. This is a mandatory field for triggers in a SIARD file, so I made the creation of the SIARD file fail for this case (that is why you get the error, it would be either an error or produce an incomplete/invalid SIARD).

I'll try to find the problem and possibly send you another release specific for this problem.

Regarding descriptions, see #174 .

**Comment by chalkos** [comment] 2016-07-18 14:40
This version logs additional information: [dbptk-app-2.0.0-beta5-228-2.zip](https://github.com/keeps/db-preservation-toolkit/files/369303/dbptk-app-2.0.0-beta5-228-2.zip)

new debug info is between
`issue 228: --------- TRIGGER RESULTSET METADATA - START`
and
`issue 228: --------- TRIGGER RESULTSET METADATA -  END`

Please try it and send me the debug info.

**Comment by PhillipTommerholt** [comment] 2016-07-19 06:14
Here is the log. It didn't get to `- END` 
[228-2.log.txt](https://github.com/keeps/db-preservation-toolkit/files/370752/228-2.log.txt)

**Comment by chalkos** [comment] 2016-07-19 08:41
I made a small mistake there :sweat_smile:

This one should be good: [dbptk-app-2.0.0-beta5-228-3.zip](https://github.com/keeps/db-preservation-toolkit/files/370995/dbptk-app-2.0.0-beta5-228-3.zip)

**Comment by PhillipTommerholt** [comment] 2016-07-19 09:57
This gave these results:
[228-3.log.txt](https://github.com/keeps/db-preservation-toolkit/files/371143/228-3.log.txt)

**Comment by chalkos** [comment] 2016-07-19 12:42
Ok, this is inconclusive until now. 

The query in SQL Server Management Studio (or anything else you are using) shows a value for `TRIGGERED_ACTION` but DBPTK "looses" this value somewhere between getting the value and writing it to the SIARD metadata xml (or maybe it doesn't event get the correct value in the first place).

I was trying to make sure the query was working correctly on DBPTK, and it seems to be from the last log you sent me.

Additional debug information is present in this version [dbptk-app-2.0.0-beta5-228-5.zip](https://github.com/keeps/db-preservation-toolkit/files/371435/dbptk-app-2.0.0-beta5-228-5.zip)
Please try it and send me the log. Thanks and sorry for having to do this in so many steps...

**Comment by chalkos** [comment] 2016-07-19 12:42
I forgot to mention, look for debug messages starting with `issue228-2: `

**Comment by PhillipTommerholt** [comment] 2016-07-19 13:17
No worries. We both have the same goal :)

Log:
[228-5.log.txt](https://github.com/keeps/db-preservation-toolkit/files/371501/228-5.log.txt)

**Comment by chalkos** [comment] 2016-07-19 14:02
Look for `issue228-3` in this one [dbptk-app-2.0.0-beta5-228-6.zip](https://github.com/keeps/db-preservation-toolkit/files/371606/dbptk-app-2.0.0-beta5-228-6.zip)

Are you able to create a small example (with different names and no data) that I can import in a SQL Server? I'm assuming this is hard, but I'm almost out of options and we might need to consider doing that. I may need to dig deeper to understand the problem, and unfortunately debug logs are pretty limiting on that front..

**Comment by PhillipTommerholt** [comment] 2016-07-20 09:13
Here is the log.
[228-6.log.txt](https://github.com/keeps/db-preservation-toolkit/files/373215/228-6.log.txt)

Let me know if I should try to create an anonymized data-empty database.

**Comment by PhillipTommerholt** [comment] 2016-07-20 09:50
Additional info which might have no value:

I have created a new database and then exported the problematic table which has the trigger. The export was without constraints, indexes, triggers etc. I then created the trigger on the copied table in the new database.
This gave no problem when exporting to SIARD2 with DBPTK.

**Comment by chalkos** [comment] 2016-07-20 10:01
> Here is the log.
> 228-6.log.txt

The log does not add anything new.
DBPTK can not get the TRIGGERED_ACTION and I don't know why, because it should be able to in normal circumstances (and it does, as you proved in your following comment).

> This gave no problem when exporting to SIARD2 with DBPTK.

I was going to ask you to try exactly that: start with a new sane/clean environment and manually re-create the minimal structure (table+trigger) to check if DBPTK can handle that.

So now we know that the problem is some configuration (maybe user permissions) on the problematic database.

Can you try to incrementally replicate more parts of the database? i.e.:
1. try to create the users, then run DBPTK to see if everything runs ok
2. add permissions, DBPTK runs ok?
3. change permissions to mimic the problematic database, DBPTK runs ok?
4. keep adding stuff and testing to see what breaks DBPTK

**Comment by PhillipTommerholt** [comment] 2016-07-21 13:19
I tried to run your sql:
```
SELECT
  o.name AS TRIGGER_NAME,
  CAST(OBJECTPROPERTY(id, 'ExecIsAfterTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsInsteadOfTrigger') AS char(1)) AS ACTION_TIME,
  CAST(OBJECTPROPERTY(id, 'ExecIsInsertTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsUpdateTrigger') AS char(1)) + CAST(OBJECTPROPERTY(id, 'ExecIsDeleteTrigger') AS char(1)) AS TRIGGER_EVENT,
  OBJECT_DEFINITION(o.id) AS TRIGGERED_ACTION,
  tab.name AS TABLE_NAME,
  s.name AS SCHEMA_NAME
FROM sysobjects o
  INNER JOIN sys.tables tab ON o.parent_obj = tab.object_id
  INNER JOIN sys.schemas s ON tab.schema_id = s.schema_id
WHERE
  o.type = 'TR'
;
```
on the original problematic database, and the newly created database (with one table and the trigger) where DBPTK has no problems exporting.

It seems that even though I scripted the trigger as create to, the trigger in the new database is not identical with the old one. There is a linebreak more in the new one. I don't know if this might be relevant?  

Old:

```

CREATE TRIGGER [triggername] ON dbo.tablename1
FOR INSERT, UPDATE
AS
  insert 
  into tablename2
  select columnname1,columnname2 = convert(int,substring(columnname3,9,6))
  from tablename1
  where columnname4 = '38' and not exists 
    (select columnname3 from tablename2 where tablename1.columname1 = tablename2.columnname1)
```

New:
```


CREATE TRIGGER [triggername] ON dbo.tablename1
FOR INSERT, UPDATE
AS
  insert 
  into tablename2
  select columnname1,columnname2 = convert(int,substring(columnname3,9,6))
  from tablename1
  where columnname4 = '38' and not exists 
    (select columnname3 from tablename2 where tablename1.columname1 = tablename2.columnname1)
```

**Comment by chalkos** [comment] 2016-07-21 13:25
Odd, but I don't think that the line breaks are causing the problem. The new one has linebreaks too and exports ok.

**Comment by PhillipTommerholt** [comment] 2016-07-22 08:58
Hi Bruno,

I have finally found the problem. 
And it was a very basic problem not related at all to triggers :sweat:

Somehow when I created the login and the user which DBPTK used to connect to the database with, I did not give the login any ownership of the db_owner schema....
I have done this in all my other extraction attempts, but I missed it here. This also explains why I couldn't reproduce the problem when I exported "the problematic table" to a new database. 

Yikes.

**Comment by chalkos** [comment] 2016-07-22 09:28
Oh well.. it was user permissions after all...
I'm closing this, as it seems to be fixed now :wink:

**Closed by chalkos** 2016-07-22 09:28 UTC
Labels: module-db: MSSQLServer, priority: Pilot blocker

**Comment by PhillipTommerholt** [comment] 2016-07-22 09:32
Yes,
Sorry for taking up your time. 
- Phillip

**Comment by chalkos** [comment] 2016-07-22 09:36
It's ok, this happens sometimes when finding/fixing bugs.
