### ISSUE TITLE
Error when unpacking SIARD based on MS Access input (UCA_METADATA)

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#163] opened 2016-03-21 08:52 UTC
Description: 
INFO [08:20:32] Handling schema structure PUBLIC
INFO [08:20:32] Handling table structure Stiki
INFO [08:20:32] Handling table structure Zadeve
INFO [08:20:32] Handling schema structure PUBLIC finished
INFO [08:20:32] Handling schema structure UCA_METADATA
INFO [08:20:32] Handling table structure PROP
INFO [08:20:32] Handling table structure TABLES
INFO [08:20:32] Handling table structure COLUMNS
INFO [08:20:32] Handling schema structure UCA_METADATA finished
INFO [08:20:32] Handling datababase structure finished
INFO [08:20:32] Exporting data for PUBLIC.Stiki
INFO [08:20:32] Exporting data for PUBLIC.Zadeve
INFO [08:20:32] Exporting data for UCA_METADATA.PROP
ERROR [08:20:32] An error occurred while handling data close table
                 Error granting permissions to public
                 ERROR: relation "uca_metadata.prop" does not exist
INFO [08:20:32] Exporting data for UCA_METADATA.TABLES
ERROR [08:20:32] An error occurred while handling data close table
                 Error granting permissions to public
                 ERROR: relation "uca_metadata.tables" does not exist
INFO [08:20:32] Exporting data for UCA_METADATA.COLUMNS
ERROR [08:20:32] An error occurred while handling data close table
                 Error granting permissions to public
                 ERROR: relation "uca_metadata.columns" does not exist
ERROR [08:20:32] Error handleing foreign key (next exception)
                 Batch entry 2 ALTER TABLE "columns" ADD FOREIGN KEY ("TABLE_ID") REFERENCES "uca_metadata"."tables" ("TABLE_ID") was aborted.  Call getNextException to see the cause.
Steps required to reproduce the bug:

1. I create a SIARD package from MS Access file. The Access file has tables Stiki and Zadeve
2. I restore to Postgresql
3. After the error I still se the tables:
   public.stiki, public.zadeve, ...,  and schema without the tables: uca_metadata

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment] 2016-03-21 12:53
Please provide a minimal example that does not contain private information and can be used to reproduce the error.

**Comment by BorisDomajnko** [comment] 2016-03-22 13:05
sent by e-mail.

**Comment by BorisDomajnko** [comment] 2016-05-30 11:31
Seems to be resolved in 2.0.0-beta4.3. The same test case is successful (and ucsmetadata tables are ignored).

**Comment by BorisDomajnko** [comment] 2016-05-30 11:52
No, another test case:
2016-05-30 13:49:14,548 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Obtaining contents from table 'UCA_METADATA.PROP'
2016-05-30 13:49:14,563 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Started data open: UCA_METADATA.PROP
2016-05-30 13:49:14,563 [main] INFO  (c.d.m.j.o.JDBCExportModule) Exporting content to table for UCA_METADATA.PROP
2016-05-30 13:49:14,563 [main] DEBUG (c.d.m.j.o.JDBCExportModule) sql: INSERT INTO "prop" VALUES (?, ?, ?, ?)
2016-05-30 13:49:14,563 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Total of 19 row(s) processed
2016-05-30 13:49:14,563 [main] ERROR (c.d.m.p.o.PostgreSQLJDBCExportModule) Error granting public read access permissions on table UCA_METADATA.PROP
org.postgresql.util.PSQLException: ERROR: relation "uca_metadata.prop" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:297)

**Comment by chalkos** [comment] 2016-05-30 12:24
Could you please verify that the first use case is really working correctly? (please ensure a clean environment before testing the use case).

I fixed an issue that should allow the export to postgresql process to complete, but with foreign key errors. Could you confirm that this is happening for the first use case?

**Comment by BorisDomajnko** [comment] 2016-05-30 12:44
No, I repeated the first use case:

d:\projekti\E-ARK>java -Xmx1g -Dfile.encoding=UTF-8 -jar dbptk-app-2.0.0-beta4.2.jar -i microsoft-access -if d:\projekti\earh\databases\mdb\OsnovnaSredstva1.accdb -e siard-2 -ef out_msa2.siard
      Converting database: microsoft-access to siard-2
      Initializing target database
      Converting database structure
log4j:WARN No appenders could be found for logger (com.healthmarketscience.jackcess.impl.DatabaseImpl).
log4j:WARN Please initialize the log4j system properly.
      Obtaining table structure for PUBLIC.Stiki
      Obtaining table structure for PUBLIC.Zadeve
      Obtaining table structure for UCA_METADATA.PROP
      Obtaining table structure for UCA_METADATA.TABLES
      Obtaining table structure for UCA_METADATA.COLUMNS
      Database structure converted
      Getting contents from table 'PUBLIC.Stiki'
      Total of 0 row(s) processed
      Obtained contents from table 'PUBLIC.Stiki'
      Getting contents from table 'PUBLIC.Zadeve'
      Total of 1 row(s) processed
WARN  Unsupported datatype: Type{description='null', originalTypeName='OTHER', sql99TypeName='CHARACTER VARYING(50)', sql2008TypeName='CHARACTER VARYING(50)'}. Using xs:string as xml type.
WARN  Unsupported datatype: Type{description='null', originalTypeName='OTHER', sql99TypeName='CHARACTER VARYING(50)', sql2008TypeName='CHARACTER VARYING(50)'}. Using xs:string as xml type.
      Obtained contents from table 'PUBLIC.Zadeve'
      Getting contents from table 'UCA_METADATA.PROP'
      Total of 19 row(s) processed
      Obtained contents from table 'UCA_METADATA.PROP'
      Getting contents from table 'UCA_METADATA.TABLES'
      Total of 4 row(s) processed
      Obtained contents from table 'UCA_METADATA.TABLES'
      Getting contents from table 'UCA_METADATA.COLUMNS'
      Total of 30 row(s) processed
      Obtained contents from table 'UCA_METADATA.COLUMNS'
WARN  Schema INFORMATION_SCHEMA was not exported because it does not contain tables.
WARN  Unsupported datatype: Type{description='null', originalTypeName='OTHER', sql99TypeName='CHARACTER VARYING(50)', sql2008TypeName='CHARACTER VARYING(50)'}. Using xs:string as xml type.
WARN  Unsupported datatype: Type{description='null', originalTypeName='OTHER', sql99TypeName='CHARACTER VARYING(50)', sql2008TypeName='CHARACTER VARYING(50)'}. Using xs:string as xml type.
WARN  Schema SYSTEM_LOBS was not exported because it does not contain tables.
      Run time 0m 1s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20160530144120864.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

d:\projekti\E-ARK>
d:\projekti\E-ARK>
d:\projekti\E-ARK>
d:\projekti\E-ARK>java -Xmx1000m -Dfile.encoding=UTF-8 -jar  dbptk-app-2.0.0-beta4.3.jar -e postgresql -eh 10.0.92.38 -edb eark_test.msa2 -eu pg_eark -ep xxx -ede -epn 5432 -i siard-2 -if out_msa2
.siard
      Converting database: siard-2 to postgresql
      Target database does not exist. Creating database eark_test.msa2
      Exporting database structure
      Exporting schema structure for schema PUBLIC
      Exporting table structure for Stiki
      Exporting table structure for Zadeve
      Exporting schema structure for schema PUBLIC
      Exporting schema structure for schema UCA_METADATA
      Exporting table structure for PROP
      Exporting table structure for TABLES
      Exporting table structure for COLUMNS
      Exporting schema structure for schema UCA_METADATA
      Exporting database structure finished
      Obtaining contents from table 'PUBLIC.Stiki'
      Exporting content to table for PUBLIC.Stiki
      Total of 0 row(s) processed
      Obtained contents from table 'PUBLIC.Stiki'
      Obtaining contents from table 'PUBLIC.Zadeve'
      Exporting content to table for PUBLIC.Zadeve
      Total of 1 row(s) processed
      Obtained contents from table 'PUBLIC.Zadeve'
      Obtaining contents from table 'UCA_METADATA.PROP'
      Exporting content to table for UCA_METADATA.PROP
      Total of 19 row(s) processed
ERROR Error granting public read access permissions on table UCA_METADATA.PROP
ERROR Error closing table UCA_METADATA.PROP
      Obtained contents from table 'UCA_METADATA.PROP'
      Obtaining contents from table 'UCA_METADATA.TABLES'
      Exporting content to table for UCA_METADATA.TABLES
      Total of 4 row(s) processed
ERROR Error granting public read access permissions on table UCA_METADATA.TABLES
ERROR Error closing table UCA_METADATA.TABLES
      Obtained contents from table 'UCA_METADATA.TABLES'
      Obtaining contents from table 'UCA_METADATA.COLUMNS'
      Exporting content to table for UCA_METADATA.COLUMNS
      Total of 30 row(s) processed
ERROR Error granting public read access permissions on table UCA_METADATA.COLUMNS
ERROR Error closing table UCA_METADATA.COLUMNS
      Obtained contents from table 'UCA_METADATA.COLUMNS'
      Adding foreign keys for table PUBLIC.Stiki
      Adding foreign keys for table PUBLIC.Zadeve
      Adding foreign keys for table UCA_METADATA.PROP
      Adding foreign keys for table UCA_METADATA.TABLES
      Adding foreign keys for table UCA_METADATA.COLUMNS
ERROR Error executing query: ALTER TABLE "columns" ADD FOREIGN KEY ("TABLE_ID") REFERENCES "uca_metadata"."tables" ("TABLE_ID")
      Finished adding foreign keys
      Run time 0m 1s
      A report was generated with a listing of information that was modified during the conversion.
      The report file is located at d:\projekti\E-ARK\dbptk-report-20160530144245704.txt
      Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

d:\projekti\E-ARK>

**Comment by chalkos** [comment] 2016-05-30 13:27
This confirms my suspicions. The process completes with foreign key errors. I think I have what I need to fix this.

**Comment by chalkos** [comment] 2016-07-05 09:18
This is partially fixed by #216 
Now a schema `public` should be created containing the MS Access tables, and another schema `UCA_METADATA` will contain metadata information (this is internal).

In the future I should be able to retrieve information from `UCA_METADATA` because it may have comments/descriptions on columns or tables.

I'm closing this issue since the error should not appear anymore. I will create a new issue to use the information in UCA_METADATA.

**Closed by chalkos** 2016-07-05 09:18 UTC
Labels: bug, MS Access
