### ISSUE TITLE
ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/db-preservation-toolkit#315] opened 2017-05-24 11:52 UTC
Description: The exporting progress stops.
(c.d.m.j.i.JDBCImportModule) Closing connection to source database
Sql error while connecting
Caused by: java.sql.SQLException: ORA-01000: maximum open cursors exceeded

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/1025363/dbptk-app.log.txt)

Attach the dbptk-app.log.txt file below.

**Comment by chalkos** [comment] 2017-05-31 11:05
A workaround to handle the database is to increase the number of cursors: https://stackoverflow.com/a/16677244

**Comment by mezeijozsef** [comment] 2017-05-31 13:31
Thank you, I'll reply soon.

**Comment by mezeijozsef** [comment] 2017-06-07 12:25
We increased the number of cursors in the spfile to 1000, but still wasn't enough. We will double it this time.

**Comment by mezeijozsef** [comment] 2017-06-07 12:42
Incresed the number to 3000 and it was able to go trough, but after reading the tables it rushed trough the export with errors at every table:
2017-06-07 14:36:12,729 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Error executing query with fetch size of 10
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01000: maximum open cursors exceeded
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/1057973/dbptk-app.log.txt)

**Comment by chalkos** [comment] 2017-06-07 12:59
It seems like the workaround is not enough to convert that database. I will update this issue when the problem is fixed.

**Comment by chalkos** [comment] 2017-06-08 10:00
this zip file contains a new experimental version in which I tried to fix the problem: [dbptk-app-2.0.0-rc2-cursors.zip](https://github.com/keeps/db-preservation-toolkit/files/1060612/dbptk-app-2.0.0-rc2-cursors.zip)

Let me know if it solves the problem.

If it doesn't, follow steps 1,2 and 3 in https://docs.oracle.com/cd/E40329_01/admin.1112/e27149/cursor.htm#OMADM5352 and comment on this issue with the results of the 3rd step (which are problematic DBPTK queries).

If no queries show up when doing the 3 steps above, try to do them while DBPTK is still running (dbptk may be outputting errors, it doesn't matter. it just needs to be running).

**Comment by mezeijozsef** [comment] 2017-06-13 08:25
The earlier attached DBPTK cursor program have failed at the beggining. Log hasn't been created.

The docs.ora guide gave these results:

> select a.value, s.username, s.sid, s.serial# from v$sesstat a, v$statname b, v$session s where a.statistic# = b.statistic#  and s.sid=a.sid and b.name = 'opened cursors current' and s.username is not null;
Results:
VALUE:6, USERNAME:POSZEIDON, SID:3, SERIAL#:1027

I rewrote this select: 

> select  sid , count(*) as "OPEN CURSORS", USER_NAME from v$open_cursor where sid=3 group by sid,user_name;
Results:
SID:3, OPEN CURSORS:7, USER_NAME:POSZEIDON

> SELECT  max(a.value) as highest_open_cur, p.value as max_open_cur FROM v$sesstat a, v$statname b, v$parameter p WHERE  a.statistic# = b.statistic#  and b.name = 'opened cursors current' and p.name= 
Results:
'open_cursors' group by p.value;

HIGHEST_OPEN_CUR:16, MAX_OPEN_CUR:3000

**Comment by chalkos** [comment] 2017-06-13 10:53
Can you provide me the console output?

The log file should now be in a folder named `logs` inside a new folder named `dbptk`.

Since version [2.0.0-rc1](https://github.com/keeps/db-preservation-toolkit/releases/tag/2.0.0-rc1) DBPTK reports and logs are placed in the `dbptk` folder.

**Comment by mezeijozsef** [comment] 2017-06-13 11:27
My bad!
[dbptk-report-20170613102252070.txt](https://github.com/keeps/db-preservation-toolkit/files/1071192/dbptk-report-20170613102252070.txt)

The console output:
![dbptk-poszeidon](https://user-images.githubusercontent.com/19432723/27080421-0e4be938-503c-11e7-9ef4-d61a9d41fdf4.png)

**Comment by chalkos** [comment] 2017-06-13 11:29
That is the report file. I need the log file which is located in the `log` folder.

**Comment by mezeijozsef** [comment] 2017-06-13 12:09
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/1071292/dbptk-app.log.txt)

**Comment by chalkos** [comment] 2017-06-13 13:30
I have identified the problem.

***

Related development notes:

```
2017-06-13 10:22:53,085 [main] DEBUG (c.d.m.j.i.JDBCImportModule) No triggers imported for POSZEIDON.COMPARATOR_RESULT
java.sql.SQLException: Closed Statement
	at oracle.jdbc.driver.OracleClosedStatement.executeQuery(OracleClosedStatement.java:3920)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:420)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTriggers(JDBCImportModule.java:1089)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableStructure(JDBCImportModule.java:533)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTables(JDBCImportModule.java:449)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:326)
	at com.databasepreservation.modules.oracle.in.Oracle12cJDBCImportModule.getSchemas(Oracle12cJDBCImportModule.java:62)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1613)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:112)
	at com.databasepreservation.Main.main(Main.java:86)
```

**Comment by chalkos** [comment] 2017-07-04 10:05
this zip file contains a new experimental version in which I tried to fix the problem: [dbptk-app-2.0.0-rc2-cursors-2.zip](https://github.com/keeps/db-preservation-toolkit/files/1121669/dbptk-app-2.0.0-rc2-cursors-2.zip)

Let me know if it solves the problem.

If it doesn't, follow steps 1,2 and 3 in https://docs.oracle.com/cd/E40329_01/admin.1112/e27149/cursor.htm#OMADM5352 and comment on this issue with the results of the 3rd step (which are problematic DBPTK queries).

If no queries show up when doing the 3 steps above, try to do them while DBPTK is still running (dbptk may be outputting errors, it doesn't matter. it just needs to be running).

In case of error please also provide me the `dbptk-app.log.txt` which should be in a folder named `logs` inside a new folder named `dbptk`.

**Comment by mezeijozsef** [comment] 2017-07-13 12:32
The experimental version did not solve the problem.

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/1145116/dbptk-app.log.txt)


This time I used the query from the 4. step. During the export, the open cursor number was constantly growing. When it reached 2600 or 2700 it jumped up to 3000 and started throwing errors and warnings. 
We will raise it again and reply.

**Comment by chalkos** [comment] 2017-07-13 12:35
There is no need to try again for now. It is clear that some cursors are not being closed.
I'll let you know when I have a new version for you to try

**Comment by Laurira** [comment] 2018-03-05 09:24
Whats the status with this issue. Our institutions in Estonia who use Oracle also get fatal error:
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
maximum open cursors exceeded

**Comment by chalkos** [comment] 2018-03-06 11:04
I will be fixing this in version 2.0.1, but I dont have a due date for that yet.

**Comment by chalkos** [comment] 2018-03-21 10:21
Please try this new version. If it works I'll make a proper release that includes this fix.

[dbptk-app-2.0.0-cursors-3.zip](https://github.com/keeps/db-preservation-toolkit/files/1832745/dbptk-app-2.0.0-cursors-3.zip)

**Comment by chalkos** [comment] 2018-03-21 10:24
Please try this new version. If it works I'll make a proper release that includes this fix.

[dbptk-app-2.0.0-cursors-3.zip](https://github.com/keeps/db-preservation-toolkit/files/1832790/dbptk-app-2.0.0-cursors-3.zip)

**Comment by Laurira** [comment] 2018-03-21 13:49
Thanks, I will try

**Comment by Laurira** [comment] 2018-03-28 14:14
This worked better. I think this error is gone. We got something new but I think this is more related to geometry. I will send you more specific description on email.

**Comment by chalkos** [comment] 2018-03-29 10:56
The geometry specific type is a complex type. I still haven't found a good way to retrieve those from the database. Most of my attempts end with the driver not being able to extract the value, so I save it to SIARD as null to be able to continue the export.

But that is a separate issue related to complex types (and user defined types). I'm closing this issue since the cursor leak problem has been fixed.

**Closed by chalkos** 2018-03-29 10:56 UTC
Labels: module-db: Oracle, type: bug

**Comment by Laurira** [comment] 2018-03-29 12:22
But why doesn't it create SIARD then? The process stopped with this SDO-problem and for example header/metadata.xml is completely empty.

**Comment by Laurira** [comment] 2018-03-29 12:27
So the problem why the incorrect SIARD was created resides somewhere else. Do you need the 2.3 GB log?

Process stopped with sentence: ERROR Fatal error while converting the database (Error while Marshalling JAXB)

Last line from log:
•	Problem processing cell value and NULL was used instead, in table `SDO_OBJEKTID_ARHIIV`, in column `GEOMEETRIA`, in the 3553389th row
