### ISSUE TITLE
SIARDDK handling of SQL identifiers

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#244] opened 2016-08-05 09:29 UTC
I have a pilot database, that stops the export process when writing tableIndex.xml.
I believe the problem occurs when it meets a column with a name that does not conform to SQL identifier as defined in tableIndex.xsd.

Error:
`Caused by: org.xml.sax.SAXParseException: cvc-pattern-valid: Value 'Modtagedato(år)' is not facet-valid with respect to pattern '(\p{L}(_|\w)*)|(".*")' for type 'SQLIdentifier'.`

see log 
[marshal.txt](https://github.com/keeps/db-preservation-toolkit/files/403476/marshal.txt)

**Comment by chalkos** [comment] 2016-08-05 10:40
@PhillipTommerholt is this a pilot blocker?

**Comment by PhillipTommerholt** [comment] 2016-08-05 10:41
Yes.

**Comment by PhillipTommerholt** [comment] 2016-08-05 11:44
It is related to this closed issue: https://github.com/keeps/db-preservation-toolkit/issues/116 
The issue was fixed but it seems now that it was only fixed for the special case and not for the general syntax for SQL identifiers.

**Comment by andreaskring** [comment] 2016-08-19 14:13
@PhillipTommerholt The issue is fixed in [this](https://drive.google.com/file/d/0B8hAEqjI-ScYRWNDbDFaOGY0ZTg/view?usp=sharing) jar. Could you test, if it is working as expected? (I will make a pull request with the fix)

**Comment by PhillipTommerholt** [comment] 2016-08-23 08:12
This is fixed :+1:

**Closed** 2016-09-01 10:15 UTC
Labels: module: SIARD-DK, priority: Pilot blocker, type: bug

**Comment by andreaskring** [comment] 2018-06-01 14:12
Hmm - seems to be working here with the latest version of the master branch. I just tried to add the test below to `/dbptk-core/src/test/java/com/databasepreservation/modules/siard/out/metadata/TestTableIndexFileStrategy.java`:

```
  @Test
  public void xshouldEscapeWhenParentesisInWord() {
    TableIndexFileStrategy tableIndexFileStrategy = new TableIndexFileStrategy(null);
    assertEquals("\"FISKK413-PROD\"", tableIndexFileStrategy.escapeString("FISKK413-PROD"));
  }
```

So it seems as if the string is escaped as expected. I don't know why you are getting a SAXParseException - maybe you could try to use the latest version of the master branch an see if this helps
