### ISSUE TITLE
MS SQL Server export of tables with different "schemas".

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#224] opened 2016-07-06 08:44 UTC
This is a pilot blocker. 

_**What I did:**_
I tried the new beta5.jar and exported to SIARDDK
I have an altered Northwind database with the regular 13 dbo.schemas + 1 schema that is not dbo.
![schemas](https://cloud.githubusercontent.com/assets/15984159/16611184/0581ffb6-4360-11e6-8bf3-fa1b148c5f34.PNG)
I used the listtables function and exported all tables.

In tableIndex.xml (same as SIARD2.0 metadata.xml) all 14 tables are indexed in an order where the 13 "dbo-tables" are first, and the 14th "non-dbo-table" is indexed as table14.
After export I can see that only 13 tables have been exported, and the first table is the 14th "non-dbo-table".

**_A general DBPTK error?_**
First I thought this was a SIARDDK problem, but I believe this is a more general problem.
When I export to SIARD2.0 i get the following metadata.xml ([metadata.zip](https://github.com/keeps/db-preservation-toolkit/files/349338/metadata.zip)) , which follows the structure:
```
<schema>
<name> dbo
<folder>
<tables> 13 tables
...
<schema>
<name> kritisk
<folder>
<tables> 1 table
```

I think there might be a problem with this ordering and it could be due to differences in the concept of "schema". I am not an expert, but this is what I think is wrong:
It seems that there is a concept of schema in the SQL standard and a slightly different in MS SQL Server. If we go to the SIARD2.0 specification at 5.2:
![conceptschema](https://cloud.githubusercontent.com/assets/15984159/16611771/b20ca68e-4363-11e6-9081-a4778acccd81.PNG)

Then I interpret this in the way that there can only be one schema in the database and this includes all the tables. Otherwise it should be stated under "tables" that it should be a "List of tables in the schema" (not in the database). 

Bottomline is that there are 14 tables in the same database. In SIARDDK we do not differentiate between schemas like this scenario and SIARDDK format requires that all tables have to be listed on one <tables>-list. The SIARDDK module indeed has to be able to export this scenario as 14 tables in the correct order, but there might be some general terminological concensus before this can be done?

This is a pilot blocker because we are trying to export a MS SQL Server database that has 8 different "schemas".

**Comment by chalkos** [comment] 2016-07-06 09:20
> After export I can see that only 13 tables have been exported, and the first table is the 14th "non-dbo-table".

Does this mean taking the SIARD and using DBPTK to load it in a DBMS? If so, which DBMS?

because this:

> the 13 "dbo-tables" are first, and the 14th "non-dbo-table" is indexed as table14

is the expected behaviour for SIARD2...

> If we go to the SIARD2.0 specification at 5.2:
> ...
> Then I interpret this in the way that there can only be one schema in the database and this includes all the tables. Otherwise it should be stated under "tables" that it should be a "List of tables in the schema" (not in the database).

In SIARD 2, in the metadata.xml, the "Database level metadata" includes an element schemas (mandatory) defined as "List of schemas in the database". This is the `<schemas>...</schemas>` element. Then we have the "Schema level metadata" (of which you posted an image) which corresponds to each `<schema>...</schema>` element.

This results in something like

```
<siardArchive ...>
  ...
  <schemas>
    <schema>
      <name>dbo</name>
      ...
      <tables>
        ...tables for this schema
      </tables>
    </schema>
    <schema>
      <name>otherschema</name>
      ...
      <tables>
        ...tables for this schema
      </tables>
    </schema>
  </schemas>
</siardArchive>
```

A database, in SIARD2 (and at least in Oracle, PostgreSQL and SQL Server), can contain multiple schemas, and each schema can contain multiple tables. Like in this image:

![screenshot of skim](https://cloud.githubusercontent.com/assets/98429/16613195/e5fac4a4-4362-11e6-84c3-6e6ede438002.png)

That being said, I believe the creation of SIARD 2 is working correctly in this case.

**Comment by PhillipTommerholt** [comment] 2016-07-06 12:51
I am only talking about the export from MS SQL Server to SIARD.

Are you saying that there is a little mistake in the SIARD2.0 spec? 
This:

![conceptschema](https://cloud.githubusercontent.com/assets/15984159/16618050/7e93f68a-4387-11e6-89e8-3a77c54c9094.PNG)

Should be:

![conceptschemanew](https://cloud.githubusercontent.com/assets/15984159/16618248/a9583b82-4388-11e6-94cd-411a85af8ab0.png)

??

**Comment by chalkos** [comment] 2016-07-06 13:01
Now I understood the source of your questions (the bigger red text helped ;)
Yes, that seems to me like a little mistake. And that should be amended. Will you handle that? Or should I do it?

By the way, I noticed another small mistake: "List of the queries stored in the schema" should be "List of the views stored in the schema", don't you agree?
(@andersbonielsen you are also welcome to comment on this).

**Comment by chalkos** [comment] 2016-07-06 13:04
@PhillipTommerholt and so in conclusion, is this a SIARD-DK specific issue?

**Comment by PhillipTommerholt** [comment] 2016-07-06 13:12
Yes, I agree with your proposed change as well.
I do not know the procedure for making changes to the spec. I was of the impression that the spec was finalized.

To conclude: this is a specific SIARDDK pilot blocker.

**Comment by andreaskring** [comment] 2016-08-02 10:53
This should be fixed in the jar file located [here](https://drive.google.com/file/d/0B8hAEqjI-ScYOGlCWGNVVlJZNWs/view?usp=sharing). The same problem occured for different schemas in PostgreSQL databases. @PhillipTommerholt Could you please check if jar in the link above is working for you?

**Comment by PhillipTommerholt** [comment] 2016-08-02 10:57
Yes. 
I will give you an answer today, together with the answer from the NULL-error.

**Comment by PhillipTommerholt** [comment] 2016-08-02 11:40
This is fixed :+1:

**Closed** 2016-08-02 11:45 UTC
Labels: module: SIARD-DK, priority: Pilot blocker, type: bug
