### ISSUE TITLE
Unexpected exception with MS Access file

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#167] opened 2016-03-31 10:46 UTC
Description: When creatign a SIARD2 file from MS Access I get an exception.

Steps required to reproduce the bug:
1. 
2. 
3. 
    java -Xmx1500m -Dfile.encoding=UTF-8 -jar dbptk-app-2.0.0-beta4.0.jar -i microsoft-access -if h:\APPL\DETEKTIVI\smucarji_2010.mdb -e siard-2 -ef out_smu1.siard

```
...
DEBUG 2016-03-31 09:53:11,365 (MsAccessUCanAccessImportModule) query: SELECT * FROM [PUBLIC].[Zaposlitve]
INFO 2016-03-31 09:53:11,708 (JDBCImportModule) 1000 rows processed
INFO 2016-03-31 09:53:12,035 (JDBCImportModule) 2000 rows processed
INFO 2016-03-31 09:53:12,347 (JDBCImportModule) 3000 rows processed
ERROR 2016-03-31 09:53:12,410 (Main) Unexpected exception
DEBUG 2016-03-31 09:53:12,441 (Main) Unexpected exception
java.lang.NullPointerException
at com.databasepreservation.modules.msAccess.in.MsAccessUCanAccessImportModule.rawToCellSimpleTypeNumericApproximate(MsAccessUCanAccessImportModule.java:108)
```

Table Zaposlitve has 9190 records. If I check the structure of this table:

```
INFO 2016-03-31 09:59:59,103 (JDBCImportModule) Check constraints were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) Triggers were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) count query: SELECT COUNT(*) FROM [PUBLIC].[Tipi_zahtevnosti]
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) Counted 4 rows
DEBUG 2016-03-31 09:59:59,103 (JDBCImportModule) getting table structure for: Zaposlitve
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Getting structure of table PUBLIC.Zaposlitve
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: null
Index: 1
Is Nullable: true
Is auto increment: true
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 2
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 4
Type name: INTEGER
Column size: 32
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 3
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericExact
ColumnType hash: 1934331804

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 4
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 5
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 8
Type name: DOUBLE
Column size: 64
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 6
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericApproximate
ColumnType hash: 1017775584

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 12
Type name: VARCHAR
Column size: 16777216
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 7
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeString
ColumnType hash: 1423142621

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 93
Type name: TIMESTAMP
Column size: 26
Decimal digits: 0
Radix: 0
Remarks: null
Default value: 2016-03-31 09:59:58.0
Index: 8
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 159857490

DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 16
Type name: BOOLEAN
Column size: 0
Decimal digits: 0
Radix: 0
Remarks: null
Default value: null
Index: 9
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeBoolean
ColumnType hash: 1332743696

INFO 2016-03-31 09:59:59,118 (JDBCImportModule) Check constraints were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Triggers were not imported: not supported yet on MsAccessUCanAccessImportModule
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) count query: SELECT COUNT(*) FROM [PUBLIC].[Zaposlitve]
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Counted 9161 rows
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) getting table structure for: PROP
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Getting structure of table UCA_METADATA.PROP
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 12
```

**Comment by chalkos** [comment] 2016-03-31 13:29
@BorisDomajnko, could you please provide me the name of the 6th column of Zaposlitve? It should have type double in MS Access (or some other floating point type). More metadata on that column (and it's type) present in MS Access is also appreciated and may help fixing this problem.

The rest of the comment are development notes. You can ignore them.

--------------

##### development notes for fixing the issue

From [MsAccessUCanAccessImportModule.java:108](https://github.com/keeps/db-preservation-toolkit/blob/816e93c2afe8c0a72dba7e5b826b74f7ea3bdd1d/dbptk-core/src/main/java/com/databasepreservation/modules/msAccess/in/MsAccessUCanAccessImportModule.java#L108):
```
protected Cell rawToCellSimpleTypeNumericApproximate(String id, String columnName, Type cellType, ResultSet rawData) throws SQLException {
  Cell cell = null;
  if ("DOUBLE".equalsIgnoreCase(cellType.getOriginalTypeName())) {
    String data = rawData.getString(columnName);
    String parts[] = data.split("E");
```

it seems that `rawData.getString(columnName);` is returning null. That also indicates that the problematic data type is
```
DEBUG 2016-03-31 09:59:59,118 (JDBCImportModule) Data type: 8
Type name: DOUBLE
Column size: 64
Decimal digits: 0
Radix: 2
Remarks: null
Default value: 0
Index: 6
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeNumericApproximate
ColumnType hash: 1017775584
```

**Comment by BorisDomajnko** [comment] 2016-03-31 13:51
The column no. 7 is Opomba (in English: "Notes"). In Access I can see only Slovenian data type, which I translate to "More lines of text".

**Comment by chalkos** [comment] 2016-03-31 13:52
Thanks, but I asked you for the 6th column name and datatype.

**Comment by BorisDomajnko** [comment] 2016-03-31 14:39
Sorry, I do not know how I mixed it (started with 0:)
The column Ure (eng. hours) is Število, in English: Number, same as columns 2 and 3.

**Comment by chalkos** [comment] 2016-03-31 15:03
So Število is the column name or the column type? (sorry, but I was not sure from reading your comment)

I think the culprit is this caracter: `Š`.

**Comment by BorisDomajnko** [comment] 2016-04-01 06:22
Število is the type - Number.
Example with data sent by mail.

**Comment by chalkos** [comment] 2016-04-01 09:42
From the example data it seems that the cause is an empty/null cell.

**Comment by BorisDomajnko** [comment] 2016-04-01 12:06
I can confirm that - I have replaced empty values with 0 and the dptk ended without java exception now.

But if the table allows NULL values, they should be allowed also in the siard2. We can not (before delivering to the achives)  ask the database owners to change the values db tables of applications which were used in production without problems. We should ingest the data "as it is".

**Comment by chalkos** [comment] 2016-04-01 12:18
> But if the table allows NULL values, they should be allowed also in the siard2.

They are, as in, the specification allows it.

> We can not (before delivering to the achives) ask the database owners to change the values db tables of applications which were used in production without problems. We should ingest the data "as it is"..

Exactly.

The problem is in dbptk and should be fairly simple to fix. Null values are supported by the application already, so it's only a matter of checking if the value is NULL and marking it as such (the rest of the application already knows how to handle them from that point).

**Closed** 2016-05-11 13:36 UTC
Labels: bug, MS Access
