### ISSUE TITLE
PostgreSQL: date/time format when extracting

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#200] opened 2016-05-19 08:06 UTC
Description: 
INSERT INTO ... VALUES ('408314', '82.190', '2008-8-21 +2:0:0', NULL) was aborted.
INSERT INTO ...  VALUES ('408335', '82.110', '2008-11-17 +1:0:0', NULL) was aborted
(dbptk-app-2.0.0-beta4.2)
1. Export from Postgresql to siard-2
2. Create create PostgreSQL -> errors occur
3.

**Comment by chalkos** [comment] 2016-05-19 08:58
Without knowing the data types it is really hard for me to narrow down the source of the problem.

Could you provide me the postgreSQL types for the columns in the problematic table?

**Comment by BorisDomajnko** [comment] 2016-05-19 12:00
All source columns with dates are DATE. No time is used. In the SIARD XML I have found for the related table:
<row><c1>408314</c1><c2>82.190</c2><c3>2008-08-21</c3></row

But at restore we get in dbptk-app.log.txt:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "prs_druge_dejavnosti" VALUES ('408314', '82.190', '2008-8-21 +2:0:0', NULL) was aborted.  Call getNextException to see the cause.

All times with exceptions are (wrong) either -2:0:0 or +2:0:0.
metadata.xml:
                <table>
                    <name>prs_druge_dejavnosti</name>
                    <folder>table22</folder>
                    <columns>
                        <column>
                            <name>enota</name>
                            <type>INTEGER</type>
                            <typeOriginal>int4</typeOriginal>
                            <nullable>false</nullable>
                        </column>
                        <column>
                            <name>sifra</name>
                            <type>CHARACTER(6)</type>
                            <typeOriginal>CHARACTER(6)</typeOriginal>
                            <nullable>true</nullable>
                        </column>
                        <column>
                            <name>datum_vpisa</name>
                            <type>DATE</type>
                            <typeOriginal>date</typeOriginal>
                            <nullable>true</nullable>
                        </column>
                        <column>
                            <name>datum_izbrisa</name>
                            <type>DATE</type>
                            <typeOriginal>date</typeOriginal>
                            <nullable>true</nullable>
                        </column>
                    </columns>
                    <checkConstraints>
                        <checkConstraint>
                            <name>17507_17694_1_not_null</name>
                            <condition>UNKNOWN</condition>
                        </checkConstraint>
                    </checkConstraints>
                    <rows>919618</rows>
                </table>

**Comment by chalkos** [comment] 2016-05-19 16:51
Could you provide me more lines from the log file near `java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "prs_druge_dejavnosti" VALUES ('408314', '82.190', '2008-8-21 +2:0:0', NULL) was aborted. Call getNextException to see the cause.` ?

The exact text is necessary for me to find what part of the code is causing this. Table names and other private info can be replaced by ########, but I need the rest of the text.

**Comment by chalkos** [comment] 2016-05-30 13:37
@BorisDomajnko thanks for the info by email, I will get back to this when possible.

Personal note: info in email. email subject is `#200`

**Comment by luis100** [comment] 2019-04-24 08:45
@chalkos is this done?

**Comment by chalkos** [comment] 2019-04-24 09:41
> @chalkos is this done?

Forwarded the logs to you.

**Comment by luis100** [comment] 2019-04-24 09:43
This needs to be run again in the original database with a new version of the DBPTK as a lot as changed since this issue was posted.

Will close this issue until such new testing can be done.

**Closed by luis100** 2019-04-24 09:43 UTC
Labels: bug, postgres
