### ISSUE TITLE
Failure at loading the LOBS: Failed to open lob at content/schema1/...

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#385] opened 2019-08-05 09:55 UTC
Cannot create a database with lobs, using dbptk-app-2.4.0.jar, 

Steps required to reproduce the bug:

1. There are more tables in the database. I exported to SIARD file with one table only (using -etf option for table10).
2.  Now I import SIARD back to PostgreSQL and get the error. I see these txt files in the siard file. Table10 is created, but it is empty.

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3466979/dbptk-app.log.txt)
Attach the dbptk-app.log.txt file below.

**Comment by hmiguim** [comment] 2019-08-05 16:51
Hello Boris,
I did the same steps trying to reproduce the bug, but couldn't reproduce.
It is ok for you to send me the .siard file so I can analyze it.

Thanks

**Comment by hmiguim** [comment] 2019-08-05 16:52
One thing that I noticed from the log that you send me you are using the version 2.3.0, go to https://github.com/keeps/db-preservation-toolkit/releases/tag/v2.4.0 and download the latest version

**Comment by BorisDomajnko** [comment] 2019-08-06 06:44
You were right, with 2.4.0 it works now.
Is there a need to concern about the compatibiliy issues regarding SIARD packages? If the archives regularly update the versions of the tools, will this have any effect on the archived packages and their usability? Further more, imagine that an archive switches from Suite to DBPTK or vice versa just in order to cover some functionality issue (e.g. supported platform). I compare this with PDF/A: once I create a file it is expected to remain PDF/A complaint also in the future. Is there any policy about it?
Kind regards.

**Comment by hmiguim** [comment] 2019-08-06 12:34
So, I made some tests. First I download the DBPTK version 2.3.0 and generate a SIARD file from a PostgreSQL DBMS with LOB (I use the sakila, a MySQL sample database as example, the table staff has a LOB, a .png file). Then I imported the SIARD to the PostgreSQL and it correctly converts the LOB. Next, I download the DBPTK version 2.4.0 and repeat the import process to PostgreSQL (using the SIARD generated by the version 2.3.0), same result, the LOB was correctly converted. I would like for you to let me check the SIARD file that was generated, and the command that you used, you can send me to email (mguimaraes@keep.pt) or as an attachment to this thread. 

Regarding the compatibility there should be no issue, SIARD should remain the same, independently the version that created the SIARD.

**Comment by BorisDomajnko** [comment] 2019-08-07 06:39
Hello Miguel,
I am sending you the siard file through the file transfer system SOVD, you
will get a notification.
The siard file was created on postgres and reused on postgres. I only
manually truncated the txt files to make it shorter for the mail, but it
was not enough.
These lines in log look strange:
File "content/schema1/table1/lob4/content/schema1/table1/lob4/record1.txt"
is ...
Regards Boris

V V pon., 5. avg. 2019 ob 18:51 je oseba Miguel Guimarães <
notifications@github.com> napisala:

**Comment by hmiguim** [comment] 2019-08-07 09:04
Hello Boris,

The version 2.4.0 of the DBPTK added some changes to the SIARD files created. Prior to the version 2.4.0 the SIARD file created had the LOB path incomplete (and it is not according the SIARD specification). This was fixed on issue #377. If you do a migration SIARD (the one that you send me) to a new SIARD with the latest version you will see that the path to the LOB is different from the SIARD generated by DBPTK 2.3.0. After the migration you can try to import the SIARD back again to PostgreSQL and should be all correctly imported.

**Comment by BorisDomajnko** [comment] 2019-08-07 10:53
ok, that explains, thank you,

**Comment by hmiguim** [comment] 2019-08-07 10:56
You're welcome. Closing this issue.

**Closed by hmiguim** 2019-08-07 10:56 UTC
