### ISSUE TITLE
SQL error while connecting to sybase database

### ISSUE THREAD

**Issue by maheshgawli** [keeps/db-preservation-toolkit#335] opened 2018-10-10 11:37 UTC
Description: 
I am executing a command to connect to sybase database and convert/extract data into siad-2 format.
while doing so, I get the below error message. Please help me to determine the issue.

Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.

Steps required to reproduce the bug:

1. Install dbptk-app-2.0.0-rc2.jar ,  jconn4.jar
2. run command.
3.  java "-Dfile.encoding=UTF-8" -cp "C:\database-archiving\dbptk-app-2.0.0-rc2.jar;C:\database-archiving\jconn4.ja
r" com.databasepreservation.Main   --import=jdbc   --import-driver=com.sybase.jdbc4.jdbc.SybDriver   --import-connection="jdbc:sybase:Tds:cdcvxxx.xxx.
com:10001?USER=login&PASSWORD=hcp
&ServiceName=test"   -e siard-2   -ef C:\mirror2.siard.zip

2018-10-10 13:28:56,081 [main] DEBUG (c.d.Main) #########################################################
2018-10-10 13:28:56,083 [main] DEBUG (c.d.Main) #   START-ID-a1d58b4e-ff05-415d-b468-a1fb6ebfd11e
2018-10-10 13:28:56,083 [main] DEBUG (c.d.Main) #   START v2.0.0-rc2
2018-10-10 13:28:56,086 [main] DEBUG (c.d.Main) #   version info: {"git.build.user.email":"chalkos@chalkos.net","git.build.host":"young","git.dirty":"false","git.remote.origin.url":"git@github.com:keeps/db-preservation-toolkit.git","git.closest.tag.name":"2.0.0-beta7.2","git.commit.id.describe-short":"2.0.0-beta7.2-14","git.commit.user.email":"chalkos@chalkos.net","git.commit.time":"04.05.2017 @ 16:27:00 WEST","git.commit.message.full":"updated version to rc2","git.build.version":"2.0.0-rc2","git.commit.message.short":"updated version to rc2","git.commit.id.abbrev":"bb6efa8","git.branch":"master","git.build.user.name":"Bruno Ferreira","git.closest.tag.commit.count":"14","git.commit.id.describe":"2.0.0-beta7.2-14-gbb6efa8","git.commit.id":"bb6efa86f3401d4cd1a7f31ec66c7037ced2ee1a","git.tags":"","git.build.time":"04.05.2017 @ 16:28:10 WEST","git.commit.user.name":"Bruno Ferreira"}
2018-10-10 13:28:56,086 [main] DEBUG (c.d.Main) #########################################################
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Operating system: Windows 7
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Architecture: amd64
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Version: 6.1
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Java vendor: Oracle Corporation
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Java version: 1.8.0_181
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Java class version: 52.0
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Default Charset reported by java: UTF-8
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) Default Charset used by StreamWriter: UTF8
2018-10-10 13:28:56,086 [main] DEBUG (c.d.c.CLI) file.encoding property: UTF-8
2018-10-10 13:28:56,091 [main] DEBUG (c.d.m.Reporter) moduleParameters, module: jdbc with parameters ## Parameters
**Import module:** jdbc
- driver = com.sybase.jdbc4.jdbc.SybDriver
- connection = jdbc:sybase:Tds:cdcvxxx.eu.xxxxx.com:10001?USER=login&PASSWORD=hcp&ServiceName=test
2018-10-10 13:28:56,102 [main] DEBUG (c.d.m.Reporter) moduleParameters, module: siard-2 with parameters **Export module:** siard-2
- file = C:\mirror2.siard.zip
- compress = false
- pretty xml = false
2018-10-10 13:28:56,109 [main] INFO  (c.d.Main) Converting database: jdbc to siard-2
2018-10-10 13:28:56,109 [main] INFO  (c.d.m.j.i.JDBCImportModule) Initializing target database
2018-10-10 13:28:56,114 [main] INFO  (c.d.m.j.i.JDBCImportModule) Converting database structure
2018-10-10 13:28:56,141 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc4.jdbc.SybDriver
2018-10-10 13:28:56,143 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection
2018-10-10 13:28:56,242 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Connected
2018-10-10 13:28:56,243 [main] DEBUG (c.d.m.j.i.JDBCImportModule) driver version: jConnect (TM) for JDBC(TM)/7.00(Build 26502)/P/EBF17993/JDK16/Thu Jun  3  3:09:09 2010
2018-10-10 13:28:56,278 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2018-10-10 13:28:56,289 [main] ERROR (c.d.Main) Connection error while importing/exporting
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1672)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)
Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.int(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.doSetParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.setParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setNull(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.getSchemas(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:285)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	... 3 common frames omitted
2018-10-10 13:28:56,290 [main] ERROR (c.d.Main) Fatal error while converting the database (SQL error while connecting)
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1672)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)
Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.int(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.doSetParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.setParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setNull(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.getSchemas(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:285)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	... 3 common frames omitted
2018-10-10 13:28:56,290 [main] INFO  (c.d.Main) Disabling connection encryption (for modules that support it) and trying again.
2018-10-10 13:28:56,291 [main] DEBUG (c.d.m.Reporter) moduleParameters, module: jdbc with parameters **Import module:** jdbc
- driver = com.sybase.jdbc4.jdbc.SybDriver
- connection = jdbc:sybase:Tds:cdcvxxx.xxx.com:10001?USER=login&PASSWORD=hcp&ServiceName=test
2018-10-10 13:28:56,291 [main] DEBUG (c.d.m.Reporter) moduleParameters, module: siard-2 with parameters **Export module:** siard-2
- file = C:\mirror2.siard.zip
- compress = false
- pretty xml = false
2018-10-10 13:28:56,291 [main] INFO  (c.d.Main) Converting database: jdbc to siard-2
2018-10-10 13:28:56,291 [main] INFO  (c.d.m.j.i.JDBCImportModule) Initializing target database
2018-10-10 13:28:56,292 [main] INFO  (c.d.m.j.i.JDBCImportModule) Converting database structure
2018-10-10 13:28:56,292 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc4.jdbc.SybDriver
2018-10-10 13:28:56,292 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection
2018-10-10 13:28:56,353 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Connected
2018-10-10 13:28:56,353 [main] DEBUG (c.d.m.j.i.JDBCImportModule) driver version: jConnect (TM) for JDBC(TM)/7.00(Build 26502)/P/EBF17993/JDK16/Thu Jun  3  3:09:09 2010
2018-10-10 13:28:56,386 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2018-10-10 13:28:56,396 [main] ERROR (c.d.Main) Connection error while importing/exporting
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1672)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:112)
	at com.databasepreservation.Main.main(Main.java:86)
Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.int(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.doSetParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.setParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setNull(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.getSchemas(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:285)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	... 3 common frames omitted
2018-10-10 13:28:56,404 [main] ERROR (c.d.Main) Fatal error while converting the database (SQL error while connecting)
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1672)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:112)
	at com.databasepreservation.Main.main(Main.java:86)
Caused by: java.sql.SQLException: JZ0SB: Parameter index out of range: 1.
	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseError(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.int(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.doSetParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.ParamManager.setParam(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybPreparedStatement.setNull(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.a(Unknown Source)
	at com.sybase.jdbc4.jdbc.SybDatabaseMetaData.getSchemas(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:285)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	... 3 common frames omitted
2018-10-10 13:28:56,414 [main] INFO  (c.d.Main) Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
2018-10-10 13:28:56,422 [main] INFO  (c.d.Main) Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
2018-10-10 13:28:56,429 [main] DEBUG (c.d.Main) #########################################################
2018-10-10 13:28:56,431 [main] DEBUG (c.d.Main) #   FINISH-ID-a1d58b4e-ff05-415d-b468-a1fb6ebfd11e
2018-10-10 13:28:56,431 [main] DEBUG (c.d.Main) #   FINISH v2.0.0-rc2
2018-10-10 13:28:56,431 [main] DEBUG (c.d.Main) #   EXIT CODE: 4
2018-10-10 13:28:56,431 [main] DEBUG (c.d.Main) #########################################################

Attach the dbptk-app.log.txt file below.

**Comment by luis100** [comment] 2018-10-11 08:18
It seems that Sybase JDBC implementation has an error or does not support the DatabaseMetaData#getSchemas() method. So, it will need a workaround to get the list of schemas, which means that a specific module for the Sybase DBMS must be developed as it does not follow strict generic JDBC model.

**Comment by luis100** [comment] 2018-10-11 09:34
@maheshgawli I noticed you haven't used the latest version and instead used RC2, could you test with [final release version](https://github.com/keeps/db-preservation-toolkit/releases/tag/2.0.0)?

**Comment by maheshgawli** [comment] 2018-10-11 09:49
Thankyou for your response luis.
last year (may 2017) one of my colleague had successfully connected to sybase db and generated the siard-2.zip file. 

Now i try to connect to oracle using  v2.0.0 . It provides a different response. PFA the file.
I am using ojdbc8.jar

[log.txt](https://github.com/keeps/db-preservation-toolkit/files/2468373/log.txt)

**Comment by luis100** [comment] 2018-10-11 10:05
This is a different issue, please refrain from getting out of scope in issues.
Also, there is an Oracle module, you should use it to connect to Oracle databases instead of using the JDBC module.

Anyway, the problem you are describing relates to an unsupported feature of the Oracle database/driver. See the following link to solve it from the side of the DBMS: https://www-01.ibm.com/support/docview.wss?uid=swg1JR52034

**Closed by luis100** 2018-10-11 10:05 UTC
Labels: type: feature

**Comment by maheshgawli** [comment] 2018-10-11 11:20
Thank you . @luis100  . I was able to connect to oracledb and export the contents. I will check if I can build some workaround for connecting to Sybase db.

**Comment by maheshgawli** [comment] 2018-10-24 08:06
@luis100 , I replaced the jconn4.jar which was downloaded from internet. 
I used the jar which was available in the company maven repository (jconn4.jar) . It worked.
So , you can drop this issue and remove the feature tag.

**Comment by luis100** [comment] 2018-10-24 08:08
@maheshgawli cool, could you add more detailed instructions on how to do this in case another user would have the same problem?

**Comment by Laurira** [comment] 2018-11-05 12:06
Actually I would be very interested how did you get it working with Sybase.

I have tried unsuccessfully jconn3.jar and jconn4.jar

**command with jconn3.jar**
java "-Dfile.encoding=UTF-8" -cp "C:\dbptk\dbptk-app-2.0.0.jar;C:\dbptk\jconn3.jar" com.databasepreservation.Main   --imp
ort=jdbc --import-driver=com.sybase.jdbc3.jdbc.SybDriver      --import-connection="jdbc:sybase:Tds:192.168.32.26:2638?USER=***&PASSWOR
D=***&ServiceName=fotod" -e siard-2 -ef fotisSyB.siard

**result**
2018-11-05 13:59:04,736 [main] INFO  (c.d.Main) Converting database: jdbc to siard-2
2018-11-05 13:59:04,736 [main] INFO  (c.d.m.j.i.JDBCImportModule) Initializing target database
2018-11-05 13:59:04,747 [main] INFO  (c.d.m.j.i.JDBCImportModule) Converting database structure
2018-11-05 13:59:04,748 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc3.jdbc.SybDriver
2018-11-05 13:59:04,748 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection
2018-11-05 13:59:04,752 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2018-11-05 13:59:04,752 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc3.jdbc.SybDriver
2018-11-05 13:59:04,752 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection
2018-11-05 13:59:04,756 [main] DEBUG (c.d.m.j.i.JDBCImportModule) could not obtain connection in order to close it
java.sql.SQLException: JZ00L: Login failed.  Examine the SQLWarnings chained to this exception for the reason(s).


**command with jconn4.jar**
java "-Dfile.encoding=UTF-8" -cp "C:\dbptk\dbptk-app-2.0.0.jar;C:\dbptk\jconn4.jar" com.databasepreservation.Main --import=jdbc --import-driver=com.sybase.jdbc4.jdbc.SybDriver --import-connection="jdbc:sybase:Tds:192.168.32.26:2638?USER=***&PASSWORD
=***&ServiceName=fotod" -e siard-2 -ef fotisSyB.siard

**result**
2018-11-05 13:38:26,553 [main] INFO  (c.d.m.j.i.JDBCImportModule) Initializing target database
2018-11-05 13:38:26,568 [main] INFO  (c.d.m.j.i.JDBCImportModule) Converting database structure
2018-11-05 13:38:26,626 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc4.jdbc.SybDriver
2018-11-05 13:38:26,629 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2018-11-05 13:38:26,629 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.sybase.jdbc4.jdbc.SybDriver
2018-11-05 13:38:26,632 [main] DEBUG (c.d.m.j.i.JDBCImportModule) could not obtain connection in order to close it
java.sql.SQLException: Could not find SQL driver class: com.sybase.jdbc4.jdbc.SybDriver
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getConnection(JDBCImportModule.java:146)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.closeConnection(JDBCImportModule.java:192)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1675)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)
Caused by: java.lang.ClassNotFoundException: com.sybase.jdbc4.jdbc.SybDriver


**What could be the issue here?**

**Comment by luis100** [comment] 2018-11-06 08:50
On the first case, with jconn3.jar, there seems to be a login failure and the details are in the SQL Warnings, which are not being shown because the stack trace of that exception is missing or not being print out.

On the second case,  jconn4.jar, the class you are referring to was not found, "com.sybase.jdbc4.jdbc.SybDriver" perhaps is misspelled or the jconn4.jar you have is not complete.

I've noticed that the Sybase webpage also refers a jTDS driver that you could try.
https://www.dbvis.com/features/sybase-ase-database-drivers/

**Comment by maheshgawli** [comment] 2018-11-06 09:33
@Laurira 
you can use the latest jar or dbptk-app-2.0.0-rc2.jar . it works for both.

Please find the command i used 
java "-Dfile.encoding=UTF-8" -cp "C:\database-archiving\dbptk-app-2.0.0-rc2.jar;C:\database-archiving\jconn4.jar" com.databasepreservation.Main --import=jdbc --import-driver=com.sybase.jdbc4.jdbc.SybDataSource   --import-connection="jdbc:sybase:Tds:cdcvxxx.xxx.
com:10001?USER=login&PASSWORD=hcp
&ServiceName=test" -e siard-2 -ef C:\mirror2.siard.zip 

I am not able to attach a jar file. hence zipped it and attached to this comment.
Please use it and u should be able to connect.



[jconn4.zip](https://github.com/keeps/db-preservation-toolkit/files/2552443/jconn4.zip)

**Comment by luis100** [comment] 2018-11-06 09:36
The change that makes it work seems to be using `--import-driver=com.sybase.jdbc4.jdbc.SybDataSource` instead of `--import-driver=com.sybase.jdbc3.jdbc.SybDriver` (against what is written in the Sybase documentation page, oh well...)

**Comment by Laurira** [comment] 2018-11-06 11:20
Thanks guys. I got it working with SybDriver

**Comment by maheshgawli** [comment] 2018-11-06 11:55
Your welcome. yes it works with com.sybase.jdbc4.jdbc.SybDriver also.
