### ISSUE TITLE
Information loss when roundtriping Oracle -> SIARD -> Oracle

### ISSUE THREAD

**Issue by mezeijozsef** [keeps/db-preservation-toolkit#232] opened 2016-07-22 11:17 UTC
Description: There is an error, while importing a SIARD into oracle schema:

![dbptk -queries](https://cloud.githubusercontent.com/assets/19432723/17055555/ce042996-500d-11e6-9c89-4bbb1be744ba.JPG)

It means: the importing can be done, but some of the data will be lost. Importing a SIARD what is for example 48 MB, and then exporting it again, we will get a 46 MB file.

Steps required to reproduce the bug:

  1. Import a SIARD into Oracle - errors
  2. Export SIARD from Oracle - smaller file

The dbptk-app.log.txt file:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/378029/dbptk-app.log.txt)

**Comment by chalkos** [comment] 2016-07-22 11:23
I will look into this.
I'm also assuming that this is needed for a pilot, is that correct?

**Comment by mezeijozsef** [comment] 2016-07-22 11:27
Yes that is correct.

**Comment by mezeijozsef** [comment] 2016-08-11 09:04
Yes i left out the first one, but now attached a new .log:

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/412833/dbptk-app.log.txt)

**Comment by chalkos** [comment] 2016-08-11 09:58
The problem is that `VARCHAR2` has a maximum size of 2000 bytes according to [this documentation](https://docs.oracle.com/cd/B28359_01/server.111/b28320/limits001.htm) and DBPTK is converting it to `VARCHAR(20)`. When inserting the values back to Oracle it fails because it uses the type `VARCHAR(20)` and there are values longer than 20 characters (the data is inserted in SIARD, so there is no data loss).

This should be an easy fix, but I should also check for similar problems with Oracle datatypes.

**Comment by chalkos** [comment] 2016-08-11 11:01
@mezeijozsef could you tell me the type of the column `BKD` in table `BK01` and schema `BUR_TMP1`?

**Comment by chalkos** [comment] 2016-08-11 11:07
Meanwhile please try this version that should fix this problem: [dbptk-app-2.0.0-SNAPSHOT-232-1.zip](https://github.com/keeps/db-preservation-toolkit/files/413011/dbptk-app-2.0.0-SNAPSHOT-232-1.zip)

**Comment by mezeijozsef** [comment] 2016-09-07 11:30
Sorry for the late answer Bruno. There are still errors during ingest. I attached the log:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/458937/dbptk-app.log.txt)

**Comment by mezeijozsef** [comment] 2016-09-07 11:44
The column type is varchar2 60byte.

**Comment by chalkos** [comment] 2016-09-07 15:14
@mezeijozsef please try this version [dbptk-app-2.0.0-SNAPSHOT-232-2.zip](https://github.com/keeps/db-preservation-toolkit/files/459530/dbptk-app-2.0.0-SNAPSHOT-232-2.zip)

**Comment by mezeijozsef** [comment] 2016-09-08 09:12
Seems like the same issue with this version:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/461229/dbptk-app.log.txt)

**Comment by chalkos** [comment] 2016-09-08 09:28
Seems like you tried the export with the old version (v2.0.0-SNAPSHOT-232-1). Could you use dbptk-app-2.0.0-SNAPSHOT-232-2 that I provided above?

**Comment by mezeijozsef** [comment] 2016-09-08 09:35
First I used the first version by mistake, i stopped the process and used the 2. version for export/import/export

**Comment by chalkos** [comment] 2016-09-08 09:38
Sorry, I started in the first error and it was the same so I checked the version and it was v2.0.0-SNAPSHOT-232-1. You are right, v2.0.0-SNAPSHOT-232-2 is used further down the logfile.

**Comment by chalkos** [comment] 2016-09-08 09:57
The issue should be fixed on this one [dbptk-app-2.0.0-SNAPSHOT-232-3.zip](https://github.com/keeps/db-preservation-toolkit/files/461315/dbptk-app-2.0.0-SNAPSHOT-232-3.zip)

**Comment by mezeijozsef** [comment] 2016-09-08 11:29
There was no error message this time and the files are the same size. Seems OK :) :+1: 

[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/461492/dbptk-app.log.txt)

**Closed** 2016-09-08 12:54 UTC
Labels: meta: needs more info, meta: waiting for feedback, module-db: Oracle, module: SIARD 2, priority: Pilot blocker, type: bug
